name: Build and Release

on:
  push:
    # tags:
      # - 'v*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller

    - name: Build binary
      run: pyinstaller --onefile request_url.py

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: request_url-${{ matrix.os }}
        path: dist/request_url*
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code again
      uses: actions/checkout@v2

    - name: Install hub
      run: |
        sudo snap install hub --classic

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        ls
        VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
        hub release create -m "Release v0.0.1" -a artifacts/request_url-macos-latest/* v0.0.1
