name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests cloudscraper pyinstaller

    - name: Build binary
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          pyinstaller --onefile --hidden-import=cloudscraper -n cloudscraper-cli-win cloudscraper-cli.py
        elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          pyinstaller --onefile --hidden-import=cloudscraper -n cloudscraper-cli-linux cloudscraper-cli.py
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          pyinstaller --onefile --hidden-import=cloudscraper -n cloudscraper-cli-mac cloudscraper-cli.py
        fi

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: cloudscraper-cli-${{ matrix.os }}
        path: dist/cloudscraper-cli*
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code again
      uses: actions/checkout@v3

    - name: Install hub
      run: |
        sudo snap install hub --classic

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        ls
        VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
        hub release create -m "$VERSION" -a artifacts/cloudscraper-cli-macos-latest/* -a artifacts/cloudscraper-cli-windows-latest/* -a artifacts/cloudscraper-cli-ubuntu-latest/* $VERSION
